version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    volumes:
      - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/campbug/
    ports:
      - "80:8080"
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - .:/var/www/html/campbug/
    links:
      - db
  db:
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    environment:
      MYSQL_DATABASE: campbug
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./containers/db/conf.d:/etc/mysql/conf.d
    ports:
      - "3314:3306"
